### ISSUE TITLE
Incorrect filepaths when paths not based on current directory of program

### ISSUE THREAD

**Issue by gurgalex** [Davejkane/riv#44]
Ex.

Running from /home/alex/github/riv:

`cargo run --release riv /home/alex/*.png`
Results in the incorrect path of

`/home/alex/github/riv//home/alex/*.png`

It should be 
`/home/alex/*.png`

**Comment by gurgalex** [comment]
Possibly related to #43

**Comment by gurgalex** [comment]
Found a crate to do tilde and environmental variable expansions.

https://docs.rs/shellexpand/1.0.0/shellexpand/fn.full.html

**Comment by Davejkane** [comment]
One other way to deal with this might be to not wrap the glob in quotes, but instead let the shell provide all the paths it finds to riv. Clap might be able to handle that.

I'll look into it. It's a bit depressing that glob doesn't handle this properly.

**Comment by Davejkane** [comment]
OK. That is going to work. But we're going to lose the context of the glob provided to the program, and it might make [#40](https://github.com/Davejkane/riv/issues/40) a bit more tricky, but this is more important. I'll push a fix in the morning, because it's going to require rewriting some of the info bar code.

**Comment by Davejkane** [comment]
This bug has been fixed by accepting multiple paths, thus allowing the shell to do the glob expansion instead.
